import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const read = (relative) => readFileSync(fileURLToPath(new URL(`../${relative}`, import.meta.url)), 'utf8')

const css = read('assets/app.css')
const html = read('index.html')
const js = read('assets/app.js')
const api = read('api.php')

test('the hidden attribute outranks every layout rule in the stylesheet', () => {
  // The bug this exists for: `.gate { display: grid }` is an author rule, and
  // author rules beat the browser's `[hidden] { display: none }` whatever the
  // specificity. The login overlay therefore never went away — the key was
  // accepted, the state loaded, and the screen did not change, which reads as a
  // dead button.
  const override = /\[hidden\]\s*\{[^}]*display:\s*none\s*!important/.test(css)
  assert.ok(override, 'app.css must contain [hidden] { display: none !important }')
})

test('every element the script hides exists in the page', () => {
  // A typo in an id makes `$( ... ).hidden = true` throw on null, which stops
  // the rest of the handler silently — the same symptom from a different cause.
  const ids = new Set()
  for (const match of js.matchAll(/\$\('([a-z0-9-]+)'\)\.hidden/g)) ids.add(match[1])
  assert.ok(ids.size > 0, 'expected the script to toggle something')

  for (const id of ids) {
    assert.ok(html.includes(`id="${id}"`), `#${id} is toggled by app.js but is not in index.html`)
  }
})

test('every tab has the panel it switches to', () => {
  const tabs = [...html.matchAll(/data-tab="([a-z]+)"/g)].map((match) => match[1])
  assert.ok(tabs.length >= 4, `expected the dashboard's tabs, found ${tabs.length}`)
  for (const tab of tabs) {
    assert.ok(html.includes(`id="panel-${tab}"`), `tab "${tab}" has no #panel-${tab}`)
  }
})

test('the login form submits rather than reloading the page', () => {
  // A submit handler that forgets preventDefault navigates away and loses the
  // key, which also looks like "nothing happened".
  assert.match(js, /gate-form'\)\.addEventListener\('submit'/)
  assert.match(js, /event\.preventDefault\(\)/)
})

test('the key is read from the field the form actually contains', () => {
  assert.match(js, /\$\('gate-key'\)\.value/)
  assert.ok(html.includes('id="gate-key"'))
})

test('decision facts carry signal-state classes', () => {
  for (const className of ['fact-met', 'fact-unmet', 'fact-neutral']) {
    assert.ok(css.includes(`.${className}`), `app.css must style .${className}`)
  }
  assert.match(js, /DECISION_SIGNAL_STATES/)
  assert.match(js, /className:\s*`fact fact-\$\{fact\.status\}`/)
  assert.match(js, /100D průměr/)
  assert.match(js, /20D high/)
  assert.match(js, /denní ATR/)
  assert.match(js, /plan\?\.leverage/)
})

test('capital tile separates USD benchmark from sats trading result', () => {
  assert.match(js, /const signedPct/)
  assert.match(js, /const capitalBenchmark/)
  assert.match(js, /startingCapitalUsd/)
  assert.match(js, /firstPositiveEquitySats/)
  assert.match(js, /tile\(\s*'Výkon od startu'/, 'dashboard must render a start benchmark tile')
  assert.match(js, /BTC.*obchody.*v sats/s)
})

test('asset price labels use adaptive decimal places by price magnitude', () => {
  assert.match(js, /const price = \(value\) => \(Number\.isFinite\(value\) \? nf\(priceFractionDigits\(value\)\)\.format\(value\)/)
  assert.match(js, /const priceFractionDigits = \(value\) => \{[\s\S]*if \(magnitude < 1\) return 4[\s\S]*if \(magnitude < 10\) return 3[\s\S]*if \(magnitude < 100\) return 2[\s\S]*if \(magnitude < 1_000\) return 1[\s\S]*return 0/)
  assert.match(js, /const quotePrice = \(value\) => \{[\s\S]*return nf\(priceFractionDigits\(value\)\)\.format\(value\)/)
})

test('strategy tab shows the selected leveraged momentum strategy', () => {
  assert.ok(html.includes('data-tab="strategy"'), 'dashboard must expose the strategy tab')
  assert.ok(html.includes('id="panel-strategy"'), 'strategy tab must have a panel')
  assert.ok(html.includes('id="strategy-rules"'), 'strategy panel must contain the rule list')
  assert.ok(html.includes('id="strategy-candidates"'), 'strategy panel must contain candidates')
  assert.match(js, /STRATEGY_RULEBOOK/)
  assert.match(js, /STRATEGY_CANDIDATES/)
  assert.match(js, /renderStrategyLab/)
  assert.match(js, /Obchodujeme jen dlouhodobou sílu/)
  assert.match(js, /TF-2L Leveraged momentum/)
  assert.match(js, /5y \+ skutečný funding/)
  assert.match(js, /risk\.market=futures,risk\.riskPct=2/)
  assert.match(js, /PA-1 Price Action Structure/)
  assert.match(js, /BTCUSD \+ FX majors/)
  assert.doesNotMatch(js, /JF-1 HTF swing S\/D/)
  assert.doesNotMatch(js, /TF-X Stop-only convex breakout/)
})

test('strategy tab renders price-action event logs without duplicating the structure matrix', () => {
  assert.doesNotMatch(html, /Price action: struktura trhu/)
  assert.doesNotMatch(html, /data-strategy-panel="structure"/)
  assert.doesNotMatch(html, /id="strategy-price-action"/)
  assert.ok(html.includes('data-strategy-panel="filled-zones"'), 'strategy tab must expose the filled-zone log')
  assert.ok(html.includes('id="strategy-filled-zones"'), 'strategy tab must contain the filled-zone log host')
  assert.ok(html.includes('data-strategy-panel="trade-events"'), 'strategy tab must expose the open-trade event log')
  assert.ok(html.includes('id="strategy-trade-events"'), 'strategy tab must contain the open-trade event log host')
  assert.match(js, /renderStrategyLab/)
  assert.match(js, /renderFilledZonesLog/)
  assert.match(js, /Otevřené obchody se přehodnocují/)
})

test('strategy switching lives in the header and redraws dashboard context', () => {
  assert.ok(html.includes('id="strategy-view"'), 'header must contain the strategy switcher')
  assert.match(js, /STRATEGY_VIEW_STORAGE/)
  assert.match(js, /selectedStrategyView = 'price-action'/)
  assert.match(js, /\|\| 'price-action'/)
  assert.match(js, /STRATEGY_VIEWS/)
  assert.match(js, /currentStrategyView/)
  assert.match(js, /renderPriceActionTiles/)
  assert.match(js, /renderPortfolioTiles/)
  assert.match(js, /renderPriceActionDecision/)
  assert.match(js, /priceActionDecisionTimeframe = '4h'/)
  assert.match(js, /PRICE_ACTION_DECISION_COLUMNS/)
  assert.match(js, /\{ id: 'zones', label: 'Demand \/ Supply' \}/)
  assert.match(js, /const riskRewardDetails = \(entry\) =>/)
  assert.match(js, /Parametry výpočtu R\/R/)
  assert.doesNotMatch(js, /\{ id: 'stop', label: 'SL' \}/)
  assert.doesNotMatch(js, /\{ id: 'tp1', label: 'TP1' \}/)
  assert.doesNotMatch(js, /\{ id: 'tp2', label: 'TP2' \}/)
  assert.doesNotMatch(js, /\{ id: 'demand', label: 'Demand' \}/)
  assert.doesNotMatch(js, /\{ id: 'supply', label: 'Supply' \}/)
  assert.match(js, /renderPriceActionDecisionTabs/)
  assert.match(js, /renderPriceActionDecisionTable/)
  assert.match(js, /50% pullback/)
  assert.doesNotMatch(js, /\{ id: 'price', label: 'Cena' \}/)
  assert.match(js, /className: 'asset-decision-price'/)
  assert.match(js, /const assetPriceLabel =/)
  assert.match(js, /text: assetPriceLabel\(asset\.symbol, assetCurrentPrice\(asset\)\)/)
  assert.doesNotMatch(js, /text: Number\.isFinite\(item\?\.price\) \? `close/)
  assert.doesNotMatch(js, /range \? `\$\{profile\.pullbackPct/)
  assert.match(js, /const priceFact = \(value, title = null, status = 'neutral'\)/)
  assert.match(js, /Struktura je flat; nevstupujeme a čekáme na potvrzení HH \+ HL nebo LH \+ LL\./)
  assert.match(js, /decisionFact\('tvorba struktury'/)
  assert.match(js, /profile\.mode === 'formation'/)
  assert.doesNotMatch(html, /Price action: struktura trhu/)
  assert.match(js, /const pullbackRange = \(entry\) =>/)
  assert.match(js, /→ \$\{quotePrice\(range\.to\)\}/)
  assert.match(js, /const passedOrWaiting = \(gate\) => gate\?\.status === 'met' \? 'met' : 'neutral'/)
  assert.doesNotMatch(js, /gate\?\.status \?\? 'neutral'/)
  assert.doesNotMatch(js, /\{ id: 'invalidation', label: 'Invalidace' \}/)
  assert.match(js, /renderPriceActionEvents/)
  assert.match(js, /nearby\$\{key\}/)
  assert.match(js, /definingCandles/)
  assert.match(js, /zoneRangeTrigger/)
  assert.match(js, /dateOnly/)
  assert.match(js, /timeframeId === '1d'/)
  assert.match(js, /filledAt/)
  assert.match(js, /renderPriceActionOpen/)
  assert.match(js, /renderPriceActionOrders/)
  assert.match(js, /renderPriceActionClosed/)
  assert.match(js, /setTableHead\('panel-open', \['Otevřeno', 'Asset', 'TF'/)
  assert.doesNotMatch(js, /Stav struktury|invalidace zapsána/)
  assert.match(js, /setTableHead\('panel-orders', \['Zadáno', 'Asset', 'TF'/)
  assert.doesNotMatch(js, /Čekající price-action profily/)
  assert.doesNotMatch(js, /\['Asset', 'Směr', 'Cena', 'Zóna', 'Pullback', 'R\/R', 'Chybí'\]/)
  assert.doesNotMatch(js, /label: 'Pravidlo'/)
  assert.match(js, /renderPriceActionRuns/)
  assert.match(js, /tile\('Kapitál'/)
  assert.match(js, /tile\(\s*'Výkon od startu'/)
  assert.match(js, /tile\(\s*'Otevřené riziko'/)
  assert.match(js, /tile\('Nerealizované P\/L'/)
  assert.match(js, /tile\(\s*'Realizované P\/L'/)
  assert.match(js, /tile\(\s*'BTC'/)
  assert.match(css, /strategy-switch/)
  assert.match(css, /pa-decision-tabs/)
  assert.match(css, /pa-decision-table/)
  assert.match(css, /width: 112px;[\s\S]*max-width: 112px/)
  assert.match(css, /\.pa-decision-cell-pullback \.fact[\s\S]*white-space: nowrap/)
  assert.match(css, /\.pa-zone-list \{[\s\S]*display: flex;[\s\S]*white-space: nowrap;/)
  assert.match(css, /zone-date-popover/)
  assert.match(css, /rr-details-popover/)
  assert.match(css, /rr-detail-tp/)
  assert.match(css, /rr-detail-sl/)
  assert.match(css, /zone-range-trigger/)
})

test('all position tables use real lifecycle timestamps and no sample trades', () => {
  assert.match(js, /when\(position\.openedAt \?\? position\.createdAt\)/)
  assert.match(js, /when\(order\.createdAt \?\? order\.placedAt\)/)
  assert.match(js, /when\(trade\.closedAt\)/)
  assert.match(js, /const rows = state\?\.positions\?\.orders \|\| \[\]/)
  assert.doesNotMatch(js, /sortedPriceActionProfiles\(\)\.filter\(\(entry\) => entry\.profile\.status === 'watch'\)/)
})

test('asset tickers open a timeframe price chart with supply and demand zones', () => {
  assert.ok(html.includes('id="asset-chart-card"'), 'dashboard must contain the asset chart below the decision table')
  assert.ok(html.includes('id="asset-chart-svg"'), 'dashboard must contain the asset chart surface')
  assert.ok(html.includes('id="asset-zone-details"'), 'dashboard must contain the asset zone validation detail below the chart')
  assert.ok(html.includes('id="equity-panel"'), 'equity chart must live in a collapsible panel')
  assert.match(js, /assetTickerButton/)
  assert.match(js, /const assetCurrentPrice =/)
  assert.match(js, /assetPriceLabel\(asset\.symbol, assetCurrentPrice\(asset\)\)/)
  assert.match(js, /renderAssetChart/)
  assert.match(js, /renderAssetZoneDetails/)
  assert.match(js, /asset-backtest-detail/)
  assert.match(js, /ready profilů/)
  assert.match(js, /zoneCandidateDetails/)
  assert.match(js, /zoneCandidateFor/)
  assert.match(js, /const displayedTradeProfile =/)
  assert.match(js, /candidate\?\.eligible/)
  assert.match(js, /candidate\.entryForMinRR/)
  assert.match(js, /title\.toLowerCase\(\), index/)
  assert.match(js, /Vstup pro min\. R\/R/)
  assert.match(js, /chartCandles/)
  assert.match(js, /const xForTime = \(time\) =>/)
  assert.match(js, /const zoneStartX = xForTime\(zone\.fvg\?\.definingCandles\?\.\[0\]\?\.time \?\? zone\.firstTime\)/)
  assert.match(js, /structure\?\.high/)
  assert.match(js, /structure\?\.recentSwings/)
  assert.match(js, /structure\?\.activeRange/)
  assert.match(js, /const developingSwing = structure\?\.developingSwing/)
  assert.match(js, /replacesCandleIndex/)
  assert.match(js, /const structurePivots = new Map\(\)/)
  assert.match(js, /leg\?\.current \? \{ \.\.\.leg\.current, kind, label: leg\.label \} : null/)
  assert.match(js, /asset-structure-pullback/)
  assert.match(js, /const rightCandlePadding =/)
  assert.match(js, /const candlePlotRight =/)
  assert.match(js, /asset-structure-line asset-structure-\$\{trend\}/)
  assert.match(js, /asset-structure-line/)
  assert.match(js, /H flat/)
  assert.match(js, /const label = swing\.label \|\| \(swing\.kind === 'high' \? 'H' : 'L'\)/)
  assert.match(js, /assetChartVisibleCandleCount/)
  assert.match(js, /candles = allCandles\.slice\(-assetChartVisibleCandleCount\)/)
  assert.match(js, /const minVisibleCandleCount = Math\.min\(allCandles\.length, 60\)/)
  assert.match(js, /const niceStep = \(value\) =>/)
  assert.match(js, /const yStep = niceStep/)
  assert.match(js, /const yTicks = \[\]/)
  assert.match(js, /assetChartVisibleCandleCount \+ direction \* step/)
  assert.match(js, /chartTimeLabel/)
  assert.match(js, /asset-time-axis/)
  assert.match(js, /direction \* step/)
  assert.match(js, /const zoomHistory = \(event\) =>/)
  assert.match(js, /chartContainer\.onwheel = zoomHistory/)
  assert.match(js, /historyRange\.oninput = \(\) =>/)
  assert.match(js, /swing\.time >= candles\[0\]\.time && swing\.time <= candles\.at\(-1\)\.time/)
  assert.match(js, /svg\.onpointermove = \(event\) =>/)
  assert.match(js, /svg\.onpointerdown = \(event\) =>/)
  assert.match(js, /asset-y-axis-hitarea/)
  assert.match(js, /assetChartYScale/)
  assert.match(js, /assetChartYDrag/)
  assert.match(js, /selectedChartZone/)
  assert.match(js, /asset-zone-hit-area/)
  assert.match(js, /Zone labels stay hidden until the user selects a zone/)
  assert.match(js, /asset-crosshair-line/)
  assert.match(js, /assetPriceLabel\(asset\.symbol, value\)/)
  assert.match(js, /event\.preventDefault\(\)/)
  assert.match(js, /viewingHistory/)
  assert.match(css, /collapsible-chart/)
  assert.match(css, /asset-price-chart/)
  assert.match(css, /asset-structure-line/)
  assert.match(css, /asset-structure-up \{ stroke: #ffffff; \}/)
  assert.match(css, /asset-structure-down \{ stroke: #ffffff; \}/)
  assert.match(css, /asset-structure-line[\s\S]*drop-shadow/)
  assert.match(css, /asset-structure-flat/)
  assert.match(css, /asset-structure-pullback/)
  assert.match(css, /asset-time-label/)
  assert.match(css, /overscroll-behavior: contain/)
  assert.match(css, /touch-action: pan-y/)
  assert.match(css, /asset-crosshair-tag/)
  assert.match(css, /asset-zone-details/)
  assert.match(css, /asset-chart-history/)
  assert.match(css, /asset-backtest-detail/)
  assert.match(css, /zone-candidate-details/)
  assert.match(css, /asset-ticker/)
  assert.match(css, /asset-zone-demand/)
  assert.match(css, /asset-zone-supply/)
})

test('charts create SVG graphics in the SVG namespace and use strategy history when available', () => {
  assert.match(js, /document\.createElementNS\(SVG_NS, tag\)/)
  assert.match(js, /const strategyHistory = state\?\.strategyEquityHistory\?\.\[view\.id\]/)
  assert.match(js, /Array\.isArray\(strategyHistory\) \? strategyHistory : state\?\.equityHistory/)
})

test('backtests tab prepares a timeframe matrix for tuned strategies', () => {
  assert.ok(html.includes('data-tab="backtests"'), 'dashboard must expose the backtests tab')
  assert.ok(html.includes('id="panel-backtests"'), 'backtests tab must have a panel')
  assert.ok(html.includes('id="strategy-backtests"'), 'backtests panel must contain a render host')
  assert.match(js, /renderBacktests/)
  assert.match(js, /renderPriceActionBacktests/)
  assert.match(js, /backtestStatus/)
  assert.match(js, /priceActionBacktestResult/)
  assert.match(js, /Backtesty: Price Action/)
  assert.match(js, /state\?\.backtests\?\.assets/)
  assert.match(js, /Win rate/)
  assert.match(js, /Prům\. držení/)
  assert.match(js, /backtestPeriod/)
  assert.match(js, /aggregateBacktestRows/)
  assert.match(js, /BACKTEST_SELECTION_STORAGE/)
  assert.match(js, /backtest-selection-row/)
  assert.match(js, /tradeLog/)
  assert.match(js, /requestBacktests/)
  assert.match(js, /command: 'run-backtests'/)
  assert.doesNotMatch(js, /kliknutím na asset zobrazíte období a metodiku/)
  assert.match(css, /backtest-matrix-table/)
  assert.match(css, /backtest-results-table/)
  assert.match(css, /backtest-included/)
  assert.match(css, /backtest-excluded/)
})

test('settings edit the selected strategy stop rather than a stale R\/R gate', () => {
  assert.ok(html.includes('id="set-stop-atr"'))
  assert.ok(!html.includes('id="set-min-rr"'))
  assert.match(js, /const payload = \{\s*\.\.\.settings,/)
  assert.match(js, /risk:\s*\{\s*\.\.\.\(settings\.risk \|\| \{\}\),/)
  assert.match(js, /strategy:\s*\{\s*\.\.\.\(settings\.strategy \|\| \{\}\),\s*stopAtr:/)
})

test('the first migrated publish persists the strategy-versioned settings', () => {
  assert.match(api, /!isset\(\$existingSettings\['strategyId'\]\)/)
  assert.match(api, /isset\(\$publishedSettings\['strategyId'\]\)/)
  assert.match(api, /writeJsonFile\(SETTINGS_FILE, \$publishedSettings\)/)
})

test('the API refuses stale PA-1 runners before they overwrite current structure', () => {
  assert.match(api, /const MIN_PRICE_ACTION_MATRIX_SCHEMA = 26/)
  assert.match(api, /\$strategyId === 'price-action-structure-v1'/)
  assert.match(api, /\(int\) \$priceActionSchema < MIN_PRICE_ACTION_MATRIX_SCHEMA/)
  assert.match(api, /fail\(409, 'Runner uses an obsolete price-action matrix schema\.'\)/)
})

test('the API refuses obsolete runners before they can renew the lease', () => {
  assert.match(api, /const RUNNER_CAPABILITIES_FILE = DATA_DIR \. '\/runner-capabilities\.json'/)
  assert.match(api, /\$priceActionSchema = \$body\['priceActionSchema'\] \?\? null/)
  assert.match(api, /!is_numeric\(\$priceActionSchema\) \|\| \(int\) \$priceActionSchema < MIN_PRICE_ACTION_MATRIX_SCHEMA/)
  assert.match(api, /\$capabilities\[\$owner\] = \[/)
  assert.match(api, /'priceActionSchema' => 0/)
  assert.match(api, /Runner has not acquired a lease with the current protocol/)
  assert.match(api, /fail\(409, 'Runner uses an obsolete price-action matrix schema\.'\)/)
})

test('the API retires the duplicate legacy Pi lease identity', () => {
  assert.match(api, /const PRIMARY_RUNNER = 'rpi-primary-v2'/)
  assert.match(api, /const RETIRED_RUNNERS = \['rpi'\]/)
  assert.match(api, /const PRIMARY_RUNNER_MARKER = DATA_DIR \. '\/primary-runner-v2\.json'/)
  assert.match(api, /in_array\(\$owner, RETIRED_RUNNERS, true\) && is_readable\(PRIMARY_RUNNER_MARKER\)/)
  assert.match(api, /\$owner === PRIMARY_RUNNER/)
  assert.match(api, /writeJsonFile\(PRIMARY_RUNNER_MARKER/)
  assert.match(api, /'reason' => 'runner identity retired'/)
  assert.match(api, /!in_array\(\$currentOwner, RETIRED_RUNNERS, true\)/)
})

test('the API overlays published PA-1 backtest summaries onto the dashboard state', () => {
  assert.match(api, /const BACKTEST_FILE = DATA_DIR \. '\/backtests\.json'/)
  assert.match(api, /\$backtests = readJsonFile\(BACKTEST_FILE, null\)/)
  assert.match(api, /\$state\['backtests'\] = \$backtests/)
  assert.match(api, /'run-backtests'/)
  assert.match(api, /case 'backtests'/)
  assert.match(js, /state\?\.backtests\?\.assets/)
})
